// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server;

namespace Server.Migrations
{
    [DbContext(typeof(DBConnector))]
    [Migration("20200916081928_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Server.Loan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("borrower_name")
                        .HasColumnType("TEXT");

                    b.Property<float>("funding_amount")
                        .HasColumnType("REAL");

                    b.Property<float>("repayment_amount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LoansInfo");

                    b.HasData(
                        new
                        {
                            Id = "44f9dbd5-251b-4d6f-8d11-17f5369d8256",
                            borrower_name = "Amelia",
                            funding_amount = 345f,
                            repayment_amount = 123f
                        },
                        new
                        {
                            Id = "44f9dbd5-251b-4d6f-8d11-17f5369d8259",
                            borrower_name = "Richard",
                            funding_amount = 456f,
                            repayment_amount = 234f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
